version: '3'

services:
  app:
    build: 
      context: letstrade-bot
    ports:
      - "8000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"